### ISSUE TITLE
feature: add ical support

### ISSUE THREAD

**Issue by offlinehacker** [unicorncoding/devevents-api#18]
Ical support with filtering capabilities would be awesome, as it would allow to have (google) calendar with all upcoming events.
As far as I checked, `devevents-api` already had ical support, was there a specific reason for its removal? I am already using `dev.events` RSS feed to stay up to date with new conferences, but having calendar view of events would also very useful.

**Comment by unicorncoding** [comment]
Hey @offlinehacker 

That's a good idea, but I am not quite sure how to incorporate it into the product without cluttering UI. Any ideas?

**Comment by unicorncoding** [comment]
@offlinehacker let me know if this is what you need: 

https://github.com/unicorncoding/devevents-web/commit/41a27fc88e86df7248ea2989e1ee96dc7f203610

**Comment by offlinehacker** [comment]
Thanks, that's perfect, i successfully synced calendar into nextcloud 🙂

**Comment by unicorncoding** [comment]
You're welcome : )
